#!/usr/bin/env python3
"""
discord_voice.py - Real-Time Voice Calling, VAD, Tone DSP & TTS System for Yuna
--------------------------------------------------------------------------------
Enables Yuna to join Discord voice channels, listen to users with adaptive Voice
Activity Detection (VAD), differentiate vocal tone and musical instruments using
hardware-accelerated NumPy DSP, transcribe complete sentences (STT) without mid-sentence
chopping or repeated loops, generate contextual AI responses, and stream back
synthesized speech (TTS) with full acoustic echo suppression.

Supports:
- Slash command `/call` (actions: join, leave, status)
- Slash command `/vc` (delegates directly to voice call manager)
- Prefix command `!call` (and `!hangup`, `!call status`)
- Adaptive RMS noise-floor tracking VAD
- Acoustic self-echo suppression via token similarity matching
- Musical performance & instrument solo detection
- Concurrent channel tracking with automatic watchdog unlock
"""

import os
import re
import sys
import time
import json
import math
import asyncio
import tempfile
import threading
import subprocess
from pathlib import Path
from typing import Optional, Dict, Any, Callable, Tuple
from collections import deque

import discord

try:
    import discord.ext.voice_recv as voice_recv
    VOICE_RECV_AVAILABLE = True
except ImportError:
    voice_recv = None
    VOICE_RECV_AVAILABLE = False

try:
    import nacl
    PYNACL_AVAILABLE = True
except ImportError:
    PYNACL_AVAILABLE = False

try:
    import numpy as np
    HAVE_NUMPY = True
except ImportError:
    np = None
    HAVE_NUMPY = False

try:
    from media_intelligence.audio.voice_dsp import CallAcousticAnalyzer, CallAcousticProfile
    HAVE_CALL_DSP = True
except Exception:
    CallAcousticAnalyzer = None
    CallAcousticProfile = None
    HAVE_CALL_DSP = False

try:
    from media_intelligence.audio.stt import fast_heuristic_speech_correct
except Exception:
    def fast_heuristic_speech_correct(t): return t

_AudioSinkBase = voice_recv.AudioSink if VOICE_RECV_AVAILABLE and voice_recv else object

WHISPER_HALLUCINATIONS = {
    "thanks for watching", "thanks for watching!", "thank you for watching",
    "thank you for watching this video", "thank you for watching!",
    "subtitles by", "subtitles by the amara.org community",
    "the end", "see you next time", "...", "", ".", "..",
    "please subscribe", "like and subscribe", "subscribe", "silence", "music",
    "watching", "transcription", "transcribed by", "captions by"
}

def collapse_repeating_phrases(text: str) -> str:
    """Collapses repetitive words or phrases generated by Whisper hallucination loops."""
    if not text:
        return ""
    # 1. Single word repetitions (e.g. 'hello hello hello' -> 'hello')
    t = re.sub(r'\b(\w+)(?:\s+\1\b)+', r'\1', text, flags=re.IGNORECASE)
    # 2. Multi-word phrase repetitions (e.g. 'how are you? how are you?' -> 'how are you?')
    t = re.sub(r'(\b\w+(?:[^\w\s]+\w+|\s+\w+)+[?.!,]?)(?:\s*\1)+', r'\1', t, flags=re.IGNORECASE)
    return t.strip()

def text_similarity(a: str, b: str) -> float:
    """Computes word token overlap similarity between two text strings."""
    if not a or not b:
        return 0.0
    wa = set(re.sub(r'[^\w\s]', '', a.lower()).split())
    wb = set(re.sub(r'[^\w\s]', '', b.lower()).split())
    if not wa or not wb:
        return 0.0
    inter = len(wa & wb)
    min_len = min(len(wa), len(wb))
    coverage = inter / min_len if min_len > 0 else 0.0
    jaccard = inter / len(wa | wb) if len(wa | wb) > 0 else 0.0
    return max(coverage, jaccard)


def load_vad_config() -> Dict[str, Any]:
    """Loads Voice Activity Detection (VAD) configuration from config.json with safe defaults."""
    cfg_file = Path(__file__).resolve().parent / "config.json"
    cfg = {}
    if cfg_file.exists():
        try:
            with open(cfg_file, "r", encoding="utf-8") as f:
                cfg = json.load(f)
        except Exception:
            pass
    return {
        "silence_threshold": float(cfg.get("vad_silence_threshold", 90.0)),
        "silence_gap": float(cfg.get("vad_silence_gap", 1.5)),
        "min_speech_duration": float(cfg.get("vad_min_speech_duration", 0.45)),
        "stt_model": str(cfg.get("stt_model", "auto")),
    }


class AIVoiceSink(_AudioSinkBase):
    """
    Audio sink with adaptive Voice Activity Detection (VAD) that captures complete
    spoken sentences once and suppresses acoustic room echo.
    """
    def __init__(
        self,
        guild_id: str,
        channel_id: str,
        silence_threshold: Optional[float] = None,
        silence_gap_threshold: Optional[float] = None,
        min_speech_duration: Optional[float] = None,
        bot_user_id: Optional[int] = None
    ):
        super().__init__()
        self.guild_id = str(guild_id)
        self.channel_id = str(channel_id)

        vad_cfg = load_vad_config()
        self.silence_threshold: float = float(silence_threshold if silence_threshold is not None else vad_cfg["silence_threshold"])
        self.silence_gap_threshold: float = float(silence_gap_threshold if silence_gap_threshold is not None else vad_cfg["silence_gap"])
        self.min_speech_duration: float = float(min_speech_duration if min_speech_duration is not None else vad_cfg["min_speech_duration"])

        self.preroll_buffer = deque(maxlen=25)  # 500ms pre-roll at 20ms/frame to preserve word attacks
        self.buffer = bytearray()
        self.lock = threading.Lock()
        self.channels = 2
        self.sample_rate = 48000
        self._frame_count = 0
        self.bot_user_id = bot_user_id
        self._voice_client = None

        # Adaptive Noise & VAD Parameters
        self.noise_floor: float = 35.0
        self.min_speech_frames: int = 3          # 60ms voiced frames (+ 500ms pre-roll) to confirm speech start
        self.speech_active_frames: int = 0
        self.post_playback_cooldown: float = 0.40    # 0.40s cooldown after bot stops speaking to discard room reverberation

        # VAD State Machine: IDLE vs SPEAKING
        self.is_speaking = False
        self.voice_frames = 0
        self.last_voice_time = 0.0
        self.speech_start_time = 0.0

        self.is_bot_speaking = False
        self.is_processing = False
        self.last_bot_speak_end = 0.0
        self.last_audio_time = 0.0
        self.last_transcript = ""
        self.last_transcript_time = 0.0
        self.last_bot_reply = ""
        self.last_bot_reply_time = 0.0

    def wants_opus(self) -> bool:
        return False

    def compute_rms(self, pcm_bytes: bytes) -> float:
        """Calculates root-mean-square amplitude of 16-bit PCM chunk."""
        if len(pcm_bytes) < 4:
            return 0.0
        if HAVE_NUMPY and np is not None:
            try:
                arr = np.frombuffer(pcm_bytes, dtype=np.int16)
                if len(arr) > 0:
                    return float(np.sqrt(np.mean(arr.astype(np.float32) ** 2)))
            except Exception:
                pass
        total = 0
        count = 0
        for i in range(0, len(pcm_bytes) - 1, 32):
            val = int.from_bytes(pcm_bytes[i:i+2], 'little', signed=True)
            total += val * val
            count += 1
        return math.sqrt(total / count) if count > 0 else 0.0

    def is_frame_speech(self, rms: float, is_continuation: bool = False) -> bool:
        """
        Determines if the frame represents active speech above background noise floor.
        Uses dual-threshold hysteresis:
        - When IDLE (is_continuation=False): requires higher amplitude to confirm onset and avoid noise triggers.
        - When SPEAKING (is_continuation=True): uses a lower sustain threshold so quiet syllables, trailing words,
          and unvoiced consonants are NOT misclassified as silence mid-sentence.
        """
        if is_continuation:
            # Sustain threshold: allow softer phonemes, breathing transitions, and word endings
            sustain_floor = max(18.0, self.noise_floor * 1.15)
            dynamic_thresh = max(float(self.silence_threshold) * 0.45, sustain_floor)
        else:
            # Onset threshold: higher barrier to prevent ambient noise / breath from falsely triggering speech start
            dynamic_thresh = max(float(self.silence_threshold), self.noise_floor * 1.6)
        return rms >= dynamic_thresh

    def write(self, user, voice_data):
        now = time.time()

        # 1. Active lock: drop all packets while bot is speaking, processing, or in post-playback cooldown
        if self.is_bot_speaking or self.is_processing:
            return
        if (now - self.last_bot_speak_end) < self.post_playback_cooldown:
            return

        # 2. SSRC Filtering: unconditionally drop packets from the bot's own SSRC
        packet = getattr(voice_data, 'packet', None)
        ssrc = getattr(packet, 'ssrc', None) if packet else None
        vc = getattr(self, 'voice_client', None) or (self._voice_client if hasattr(self, '_voice_client') else None)
        if vc and hasattr(vc, 'ssrc') and ssrc is not None and ssrc == vc.ssrc:
            return

        # 3. Source user check: drop if source is a bot or matches our bot user ID
        source_user = getattr(voice_data, 'source', None) or user or getattr(voice_data, 'user', None)
        if source_user:
            if getattr(source_user, 'bot', False):
                return
            if self.bot_user_id and getattr(source_user, 'id', None) == self.bot_user_id:
                return
        elif ssrc is not None and vc and hasattr(vc, '_ssrc_to_id'):
            uid = vc._ssrc_to_id.get(ssrc)
            if uid and self.bot_user_id and uid == self.bot_user_id:
                return

        pcm = getattr(voice_data, 'pcm', None)
        if not isinstance(pcm, (bytes, bytearray, memoryview)):
            return
        pcm = bytes(pcm)
        if len(pcm) in (1920, 3840):
            self.channels = 1 if len(pcm) == 1920 else 2

        rms = self.compute_rms(pcm)

        with self.lock:
            if not self.is_speaking:
                is_speech = self.is_frame_speech(rms, is_continuation=False)
                # Track ambient background noise floor adaptively when quiet
                if rms < 120:
                    self.noise_floor = max(15.0, min(75.0, 0.96 * self.noise_floor + 0.04 * rms))
                self.preroll_buffer.append(pcm)

                if is_speech:
                    self.voice_frames += 1
                    # Require consecutive voice frames to confirm genuine speech start (rejects clicks/pops)
                    if self.voice_frames >= self.min_speech_frames:
                        self.is_speaking = True
                        self.speech_start_time = now
                        self.last_voice_time = now
                        self.speech_active_frames = self.voice_frames
                        # Transfer pre-roll audio into speech buffer so word attacks are preserved
                        for p in self.preroll_buffer:
                            self.buffer.extend(p)
                        self.preroll_buffer.clear()
                else:
                    self.voice_frames = max(0, self.voice_frames - 1)
            else:
                is_speech = self.is_frame_speech(rms, is_continuation=True)
                # Currently in speech session: accumulate all frames (speech + natural micro-pauses)
                self.buffer.extend(pcm)
                self._frame_count += 1
                if is_speech:
                    self.last_voice_time = now
                    self.speech_active_frames += 1

    def check_flush(self) -> Optional[Tuple[bytes, int]]:
        """Returns the full utterance audio ONCE the user has finished speaking."""
        if not self.is_speaking or self.is_bot_speaking or self.is_processing:
            return None
        now = time.time()
        if (now - self.last_bot_speak_end) < self.post_playback_cooldown:
            return None

        with self.lock:
            silence_gap = now - self.last_voice_time
            speech_dur = now - self.speech_start_time
            min_bytes = int(48000 * 2 * self.channels * self.min_speech_duration)

            # Adaptive silence gap threshold:
            # If user has only spoken very briefly (< 1.4s) or just opening words like "Hey Yuna...",
            # give an extra +0.35s window so mid-sentence thinking pauses don't cut them off!
            effective_gap = self.silence_gap_threshold + (0.35 if speech_dur < 1.4 else 0.0)

            # User finished speaking:
            # - At least effective_gap pause after speech (natural pause tolerance)
            # - Total audio length >= min_speech_duration
            # - Sufficient voiced phonemes (at least 6 active frames = 120ms)
            # OR hard safety phrase limit (30.0s)
            if ((silence_gap >= effective_gap and len(self.buffer) >= min_bytes and self.speech_active_frames >= 6)
                or speech_dur >= 30.0):
                audio = bytes(self.buffer)
                self.buffer.clear()
                self.preroll_buffer.clear()
                self.is_speaking = False
                self.voice_frames = 0
                self.speech_active_frames = 0
                self.is_processing = True  # Atomic lock set at flush time to prevent buffer race
                ch = self.channels if self.channels in (1, 2) else 2
                return audio, ch

            # If user made a tiny transient sound that wasn't actual speech (click, pop, cough, brief breath)
            # and stopped talking, cleanly discard it after silence_gap without locking or triggering AI
            if silence_gap >= self.silence_gap_threshold and (len(self.buffer) < min_bytes or self.speech_active_frames < 6):
                self.buffer.clear()
                self.preroll_buffer.clear()
                self.is_speaking = False
                self.voice_frames = 0
                self.speech_active_frames = 0
                return None

        return None

    def cleanup(self):
        with self.lock:
            self.buffer.clear()
            self.preroll_buffer.clear()
            self.is_speaking = False
            self.voice_frames = 0
            self.speech_active_frames = 0
            self.is_processing = False
            self.is_bot_speaking = False

    def get_audio(self) -> bytes:
        with self.lock:
            return bytes(self.buffer)

    def clear(self):
        with self.lock:
            self.buffer.clear()
            self.preroll_buffer.clear()
            self.is_speaking = False
            self.voice_frames = 0
            self.speech_active_frames = 0


class VoiceCallManager:
    """Manages active Discord voice call sessions, listen loops, tone DSP, and TTS playback."""
    def __init__(self):
        # guild_id (str) -> dict: {vc, sink, task, channel_id, start_time}
        self.sessions: Dict[str, Dict[str, Any]] = {}
        self.client: Optional[discord.Client] = None
        self.ask_ai_fn: Optional[Callable] = None
        self.speak_fn: Optional[Callable] = None
        self.transcribe_fn: Optional[Callable] = None
        self.send_msg_fn: Optional[Callable] = None

    def initialize(
        self,
        client: discord.Client,
        ask_ai_fn: Callable,
        speak_fn: Callable,
        transcribe_fn: Callable,
        send_msg_fn: Callable
    ):
        self.client = client
        self.ask_ai_fn = ask_ai_fn
        self.speak_fn = speak_fn
        self.transcribe_fn = transcribe_fn
        self.send_msg_fn = send_msg_fn

    def get_session(self, guild_id: Any) -> Optional[Dict[str, Any]]:
        return self.sessions.get(str(guild_id))

    def is_in_call(self, guild_id: Any) -> bool:
        session = self.get_session(guild_id)
        if not session:
            return False
        vc = session.get("vc")
        return bool(vc and vc.is_connected())

    def set_vad_gap(self, guild_id: Any, gap: float) -> bool:
        """Sets the VAD silence gap in seconds for an active call or all sessions."""
        updated = False
        target_gid = str(guild_id) if guild_id else None
        for gid, sess in self.sessions.items():
            if target_gid is None or gid == target_gid:
                sink = sess.get("sink")
                if sink:
                    sink.silence_gap_threshold = max(0.8, float(gap))
                    updated = True
        return updated

    def set_vad_threshold(self, guild_id: Any, threshold: float) -> bool:
        """Sets the VAD RMS silence threshold for an active call or all sessions."""
        updated = False
        target_gid = str(guild_id) if guild_id else None
        for gid, sess in self.sessions.items():
            if target_gid is None or gid == target_gid:
                sink = sess.get("sink")
                if sink:
                    sink.silence_threshold = max(30.0, float(threshold))
                    updated = True
        return updated

    def get_vad_info(self, guild_id: Any) -> Dict[str, Any]:
        """Returns the current VAD settings and runtime stats."""
        session = self.get_session(guild_id)
        if session and session.get("sink"):
            sink = session["sink"]
            return {
                "silence_gap": sink.silence_gap_threshold,
                "silence_threshold": sink.silence_threshold,
                "noise_floor": round(sink.noise_floor, 1),
                "is_speaking": sink.is_speaking,
            }
        cfg = load_vad_config()
        return {
            "silence_gap": cfg["silence_gap"],
            "silence_threshold": cfg["silence_threshold"],
            "noise_floor": 35.0,
            "is_speaking": False,
        }

    def set_stt_model(self, guild_id: Any, model: str) -> str:
        """Sets the active STT model for a server or globally."""
        clean = (model or "auto").strip().lower()
        target_gid = str(guild_id) if guild_id else None
        for gid, sess in self.sessions.items():
            if target_gid is None or gid == target_gid:
                sess["stt_model"] = clean
        return clean

    def get_stt_model(self, guild_id: Any) -> str:
        """Returns the configured or active STT model for the specified guild."""
        session = self.get_session(guild_id)
        if session and session.get("stt_model"):
            return session["stt_model"]
        cfg = load_vad_config()
        return str(cfg.get("stt_model", "auto"))

    async def start_call(self, member: discord.Member, text_channel: discord.abc.Messageable) -> Tuple[bool, str]:
        """Connects to the voice channel member is in and begins VAD listening."""
        if not PYNACL_AVAILABLE:
            return False, "❌ PyNaCl library is not installed. Voice features are disabled."
        if not VOICE_RECV_AVAILABLE:
            return False, "❌ discord-ext-voice-recv library is not installed."

        if not member.voice or not member.voice.channel:
            return False, "You need to be in a voice channel first to start a call!"

        vc_channel = member.voice.channel
        guild_id = str(member.guild.id)
        ch_id = str(getattr(text_channel, 'id', 0))

        # Check bot permissions in voice channel
        perms = vc_channel.permissions_for(member.guild.me)
        if not perms.connect:
            return False, f"❌ I don't have permission to connect to **{vc_channel.name}**! Please check my server roles."
        if not perms.speak:
            return False, f"❌ I don't have permission to speak in **{vc_channel.name}**!"

        # Disconnect any old dead session
        old_session = self.sessions.get(guild_id)
        if old_session:
            old_vc = old_session.get("vc")
            if old_vc and old_vc.is_connected():
                if old_vc.channel and old_vc.channel.id == vc_channel.id:
                    return True, f"I'm already in **{vc_channel.name}** with you! Talk anytime, I'm listening~"
                else:
                    await self.stop_call(member.guild)

        existing_vc = member.guild.voice_client
        if existing_vc and existing_vc.is_connected():
            if existing_vc.channel and existing_vc.channel.id == vc_channel.id:
                return True, f"I'm already in **{vc_channel.name}** with you! Talk anytime, I'm listening~"
            try:
                if hasattr(existing_vc, 'stop_listening'):
                    existing_vc.stop_listening()
                await existing_vc.disconnect(force=True)
                await asyncio.sleep(0.4)
            except Exception:
                pass

        try:
            print(f"[VOICE] Connecting to VC '{vc_channel.name}' (Guild: {member.guild.name})...")
            vc = await vc_channel.connect(cls=voice_recv.VoiceRecvClient, timeout=25.0, reconnect=True, self_deaf=False)
            bot_id = self.client.user.id if (self.client and self.client.user) else None
            vad_cfg = load_vad_config()
            sink = AIVoiceSink(
                guild_id,
                ch_id,
                silence_threshold=vad_cfg["silence_threshold"],
                silence_gap_threshold=vad_cfg["silence_gap"],
                min_speech_duration=vad_cfg["min_speech_duration"],
                bot_user_id=bot_id
            )
            vc.listen(sink)

            task = asyncio.create_task(self._vc_listen_loop(guild_id, ch_id))
            self.sessions[guild_id] = {
                "vc": vc,
                "sink": sink,
                "task": task,
                "channel_id": ch_id,
                "vc_channel_id": str(vc_channel.id),
                "start_time": time.time(),
                "caller_name": member.display_name,
                "stt_model": self.get_stt_model(guild_id),
            }

            # Play friendly entrance greeting
            asyncio.create_task(self._play_greeting(guild_id, member.display_name))

            return True, f"📞 Joined **{vc_channel.name}**! Voice call active — talk naturally, I'm listening!"
        except Exception as e:
            print(f"[VOICE ERROR] Failed to connect: {e}")
            return False, f"Failed to connect to voice channel: {e}"

    async def stop_call(self, guild: discord.Guild) -> Tuple[bool, str]:
        """Disconnects from the voice channel in the specified guild and cleans up."""
        guild_id = str(guild.id)
        session = self.sessions.pop(guild_id, None)
        if not session:
            if guild.voice_client and guild.voice_client.is_connected():
                try:
                    if hasattr(guild.voice_client, 'stop_listening'):
                        guild.voice_client.stop_listening()
                    await guild.voice_client.disconnect(force=True)
                    return True, "📴 Disconnected from voice channel."
                except Exception as e:
                    return False, f"Disconnect error: {e}"
            return False, "I'm not currently in any voice call in this server."

        vc = session.get("vc")
        task = session.get("task")
        sink = session.get("sink")

        if task and not task.done():
            task.cancel()
            try:
                await task
            except asyncio.CancelledError:
                pass

        if vc and vc.is_connected():
            try:
                vc.stop_listening()
            except Exception:
                pass
            try:
                await vc.disconnect(force=True)
            except Exception as e:
                print(f"[VOICE] Disconnect error: {e}")

        if sink:
            sink.cleanup()

        return True, "📴 Call ended. Disconnected from voice channel."

    async def _play_greeting(self, guild_id: str, caller_name: str):
        """Plays an in-character welcome greeting into the voice call."""
        await asyncio.sleep(0.8)
        if not self.speak_fn:
            return
        greeting_text = f"Hey {caller_name}! I'm in the call with you now. What's on your mind?"
        session = self.get_session(guild_id)
        sink = session.get("sink") if session else None
        if sink:
            sink.last_bot_reply = re.sub(r'[^\w\s]', '', greeting_text).strip().lower()
            sink.last_bot_reply_time = time.time()
        try:
            audio = await self.speak_fn(greeting_text, force=True)
            if audio:
                await self.play_vc_audio(guild_id, audio)
        except Exception as e:
            print(f"[VOICE GREETING ERROR] {e}")

    async def play_vc_audio(self, guild_id: str, mp3_bytes: bytes):
        """Streams synthesized speech (mp3 bytes) into the voice channel."""
        session = self.get_session(guild_id)
        if not session:
            return
        vc = session.get("vc")
        sink = session.get("sink")
        if not vc or not vc.is_connected():
            if sink:
                sink.is_processing = False
                sink.is_bot_speaking = False
            return

        tmp_path = None
        try:
            tmp_fd, tmp_path = tempfile.mkstemp(suffix=".mp3")
            os.close(tmp_fd)
            with open(tmp_path, "wb") as f:
                f.write(mp3_bytes)

            source = discord.FFmpegPCMAudio(tmp_path)

            now = time.time()
            if sink:
                sink.is_bot_speaking = True
                sink.last_audio_time = now
                sink.clear()

            def _after_playback(err):
                if err:
                    print(f"[VOICE] Playback finished with error: {err}")
                else:
                    print("[VOICE] TTS Playback finished.")
                if sink:
                    sink.clear()
                    sink.last_bot_speak_end = time.time()
                    sink.last_audio_time = time.time()
                    sink.is_bot_speaking = False
                    sink.is_processing = False

            # Watchdog timeout to prevent voice lock if Discord misses the after callback
            est_dur = max(5.0, (len(mp3_bytes) / 10000.0) + 4.0)
            async def _watchdog(expected_ts):
                await asyncio.sleep(est_dur)
                if sink and sink.is_bot_speaking and sink.last_audio_time == expected_ts:
                    print("[VOICE WATCHDOG] Auto-clearing bot speaking lock after timeout.")
                    sink.clear()
                    sink.last_bot_speak_end = time.time()
                    sink.is_bot_speaking = False
                    sink.is_processing = False
            asyncio.create_task(_watchdog(now))

            if vc.is_playing():
                vc.stop()
            vc.play(source, after=_after_playback)
        except Exception as e:
            print(f"[VOICE] Playback error: {e}")
            if sink:
                sink.is_bot_speaking = False
                sink.is_processing = False
        finally:
            if tmp_path:
                async def _cleanup(p):
                    await asyncio.sleep(45)
                    try:
                        if os.path.exists(p):
                            os.remove(p)
                    except Exception:
                        pass
                asyncio.create_task(_cleanup(tmp_path))

    async def _process_vc_audio(self, guild_id: str, channel_id: str, audio_bytes: bytes, channels: int = 2):
        """Converts raw audio bytes, runs STT transcription, queries AI, and speaks response."""
        session = self.get_session(guild_id)
        sink = session.get("sink") if session else None

        min_bytes = int(48000 * 2 * channels * 0.35)
        if not audio_bytes or len(audio_bytes) < min_bytes:
            if sink:
                sink.is_processing = False
            return

        caller_name = session.get("caller_name", "User") if session else "User"
        ch_eff = channels if channels in (1, 2) else 2
        dur_sec = len(audio_bytes) / (48000 * 2 * ch_eff)
        print(f"[VOICE] User finished speaking ({dur_sec:.1f}s audio). Transcribing complete sentence...")

        pcm_path = wav_path = None
        try:
            # 1. Real-Time Acoustic & Tone DSP Analysis (NumPy)
            acoustic_profile = None
            if HAVE_CALL_DSP and CallAcousticAnalyzer:
                try:
                    acoustic_profile = CallAcousticAnalyzer.analyze_pcm(audio_bytes, channels=channels, sample_rate=48000)
                except Exception as dsp_err:
                    print(f"[VOICE DSP ERROR] {dsp_err}")

            # 2. Filter out non-speech transient noise (clicks, pops, ambient mic noise)
            if acoustic_profile and acoustic_profile.is_noise_only:
                if dur_sec >= 0.4 and acoustic_profile.rms_db > -42.0:
                    print(f"[VOICE DSP] Marginally classified as noise but passing to Whisper (RMS={acoustic_profile.rms_db:.1f}dB, Dur={dur_sec:.2f}s)")
                else:
                    print(f"[VOICE DSP FILTER] Ignored ambient noise/click (ZCR={acoustic_profile.zcr:.2f}, RMS={acoustic_profile.rms_db:.1f}dB, Dur={acoustic_profile.duration_sec:.1f}s)")
                    if sink:
                        sink.is_processing = False
                    return

            tmp_fd, pcm_path = tempfile.mkstemp(suffix=".pcm")
            os.close(tmp_fd)
            with open(pcm_path, "wb") as f:
                f.write(audio_bytes)

            tmp_fd, wav_path = tempfile.mkstemp(suffix=".wav")
            os.close(tmp_fd)
            ch = channels if channels in (1, 2) else 2
            cmd = [
                "ffmpeg", "-y", "-f", "s16le", "-ar", "48000", "-ac", str(ch), "-i", pcm_path,
                "-af", "highpass=f=40",
                "-ar", "16000", "-ac", "1", "-acodec", "pcm_s16le", wav_path
            ]
            res = subprocess.run(cmd, capture_output=True, timeout=30)
            if not os.path.exists(wav_path) or os.path.getsize(wav_path) < 1024:
                if sink:
                    sink.is_processing = False
                return

            with open(wav_path, "rb") as f:
                wav_bytes = f.read()

            text = ""
            active_stt_m = self.get_stt_model(guild_id)
            if self.transcribe_fn:
                try:
                    text_res, err = await self.transcribe_fn(wav_bytes, "audio.wav", model=active_stt_m)
                except TypeError:
                    text_res, err = await self.transcribe_fn(wav_bytes, "audio.wav")
                if not err and text_res:
                    text = text_res.strip()

            # Collapse repeating words / phrases from Whisper hallucination loops
            text = collapse_repeating_phrases(text)
            text = fast_heuristic_speech_correct(text)

            cleaned_text = re.sub(r'[^\w\s]', '', text).strip().lower()
            is_hallucination = (cleaned_text in WHISPER_HALLUCINATIONS or len(cleaned_text) < 2)

            now = time.time()

            # 3. Non-Verbal Audio & Environmental Background Noise Handling
            is_nonverbal_event = False
            if is_hallucination or not text:
                if acoustic_profile:
                    if acoustic_profile.is_musical and acoustic_profile.duration_sec >= 1.0:
                        music_sig = f"music_{acoustic_profile.musical_type}"
                        if sink and sink.last_transcript == music_sig and (now - sink.last_transcript_time) < 12.0:
                            if sink:
                                sink.is_processing = False
                            return
                        if sink:
                            sink.last_transcript = music_sig
                            sink.last_transcript_time = now
                        is_nonverbal_event = True
                        text = f"*[Played {acoustic_profile.musical_desc}]*"
                    elif acoustic_profile.is_laughter and acoustic_profile.duration_sec >= 0.4:
                        if sink and sink.last_transcript == "laughter" and (now - sink.last_transcript_time) < 8.0:
                            if sink:
                                sink.is_processing = False
                            return
                        if sink:
                            sink.last_transcript = "laughter"
                            sink.last_transcript_time = now
                        is_nonverbal_event = True
                        text = "*[Laughs / chuckles into the microphone]*"
                    elif acoustic_profile.is_sigh and acoustic_profile.duration_sec >= 0.6:
                        if sink and sink.last_transcript == "sigh" and (now - sink.last_transcript_time) < 8.0:
                            if sink:
                                sink.is_processing = False
                            return
                        if sink:
                            sink.last_transcript = "sigh"
                            sink.last_transcript_time = now
                        is_nonverbal_event = True
                        text = "*[Lets out a heavy sigh into the microphone]*"
                    elif acoustic_profile.is_whisper and acoustic_profile.duration_sec >= 0.4:
                        is_nonverbal_event = True
                        text = "*[Whispers softly into the microphone]*"
                    elif acoustic_profile.is_shout and acoustic_profile.duration_sec >= 0.3:
                        is_nonverbal_event = True
                        text = "*[Loud vocal exclamation / shout]*"
                    elif acoustic_profile.background_noise in ("music", "voices_chatter") and acoustic_profile.duration_sec >= 1.2 and acoustic_profile.rms_db > -32.0:
                        noise_sig = f"bg_{acoustic_profile.background_noise}"
                        if sink and sink.last_transcript == noise_sig and (now - sink.last_transcript_time) < 15.0:
                            if sink:
                                sink.is_processing = False
                            return
                        if sink:
                            sink.last_transcript = noise_sig
                            sink.last_transcript_time = now
                        is_nonverbal_event = True
                        text = f"*[Background sound: {acoustic_profile.noise_desc}]*"

                if not is_nonverbal_event:
                    # Transient click, desk tap, or empty silence
                    if sink:
                        sink.is_processing = False
                    return

            # 4. Speech Deduplication & Acoustic Echo Suppression
            if sink and not is_nonverbal_event:
                # Block bot self-echo: mic picked up what the bot JUST said out of the speakers!
                if sink.last_bot_reply and (now - sink.last_bot_reply_time) < 12.0:
                    echo_sim = text_similarity(cleaned_text, sink.last_bot_reply)
                    if echo_sim > 0.65:
                        print(f"[VOICE ECHO SUPPRESSED] Bot self-echo transcript ({echo_sim*100:.0f}% match): '{text}'")
                        sink.is_processing = False
                        return

                sink.last_transcript = cleaned_text
                sink.last_transcript_time = now

            now_str = time.strftime("%H:%M:%S")
            tone_info = acoustic_profile.tone if acoustic_profile else "Natural"
            noise_info = f" | Room: {acoustic_profile.noise_desc}" if (acoustic_profile and acoustic_profile.noise_desc and acoustic_profile.background_noise != "quiet") else ""
            print(f"\033[92m[{now_str}] [VOICE LOG] [DISCORD VC] Heard from {caller_name}: \"{text}\" [STT: {active_stt_m}] | Tone: {tone_info}{noise_info}\033[0m")

            guild = self.client.get_guild(int(guild_id)) if self.client else None
            if not self.ask_ai_fn:
                if sink:
                    sink.is_processing = False
                return

            # 5. Generate Tone & Acoustic Context Prompt for AI
            prompt_ctx = acoustic_profile.get_prompt_context(caller_name) if acoustic_profile else ""
            ai_prompt = f"{prompt_ctx}\n{text}" if prompt_ctx else text

            try:
                reply, err = await self.ask_ai_fn(
                    channel_id,
                    ai_prompt,
                    guild=guild,
                    is_dm=False,
                    audio_bytes=wav_bytes,
                    audio_mime="audio/wav"
                )
            except TypeError:
                reply, err = await self.ask_ai_fn(channel_id, ai_prompt, guild=guild, is_dm=False)

            if err or not reply:
                if sink:
                    sink.is_processing = False
                return

            # Record bot's reply text to suppress room echo
            if sink:
                clean_reply = re.sub(r'[^\w\s]', '', reply).strip().lower()
                sink.last_bot_reply = clean_reply
                sink.last_bot_reply_time = time.time()

            print(f"\033[95m[{now_str}] [VOICE LOG] [DISCORD VC] AI Reply: \"{reply.strip()}\"\033[0m")

            # Mirror transcript to text channel with tone & background ambiance indicator
            if guild and self.send_msg_fn:
                ch_obj = guild.get_channel(int(channel_id))
                if ch_obj and isinstance(ch_obj, discord.TextChannel):
                    try:
                        icon = "🎶" if (acoustic_profile and acoustic_profile.is_musical) else ("😂" if (acoustic_profile and acoustic_profile.is_laughter) else ("🗣️"))
                        tone_tag = f" *({acoustic_profile.tone})*" if acoustic_profile else ""
                        noise_tag = f" 🎧 *[{acoustic_profile.noise_desc}]*" if (acoustic_profile and acoustic_profile.noise_desc and acoustic_profile.background_noise != "quiet") else ""
                        await self.send_msg_fn(ch_obj, f"{icon} **Voice ({caller_name}):**{tone_tag}{noise_tag} {text}\n🎙️ **AI:** {reply.strip()}")
                    except Exception:
                        pass

            # Speak answer into VC
            if self.speak_fn:
                audio = await self.speak_fn(reply, force=True)
                if audio:
                    await self.play_vc_audio(guild_id, audio)
                else:
                    if sink:
                        sink.is_processing = False
            else:
                if sink:
                    sink.is_processing = False
        except Exception as e:
            print(f"[VOICE PROCESSING ERROR] {e}")
            if sink:
                sink.is_processing = False
        finally:
            for p in (pcm_path, wav_path):
                if p and os.path.exists(p):
                    try:
                        os.remove(p)
                    except Exception:
                        pass

    async def _vc_listen_loop(self, guild_id: str, channel_id: str):
        """Background loop continuously polling the AIVoiceSink buffer for completed user speech."""
        while True:
            await asyncio.sleep(0.12)
            session = self.get_session(guild_id)
            if not session:
                print(f"[VOICE] Session ended for guild {guild_id}, stopping listen loop.")
                break
            sink = session.get("sink")
            if not sink or sink.is_bot_speaking or sink.is_processing:
                continue
            flush_res = await asyncio.get_event_loop().run_in_executor(None, sink.check_flush)
            if flush_res:
                audio, ch = flush_res
                await self._process_vc_audio(guild_id, channel_id, audio, channels=ch)


# Singleton instance
voice_manager = VoiceCallManager()
